fix: Packet.parse() shouldn't return undefined
If the packet is invalid, throw the parse error instead of:

    TypeError: Cannot match against 'undefined' or 'null'.

when using the return value.